version: "3"

services:
  web:
    build:
      dockerfile: Dockerfile.web
      context: ./
    depends_on:
      - postgres
      - redis
    env_file:
      - src/auction_db.env
      - .env
    ports:
      - "8080:80"
  postgres:
    image: postgres:14.2-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
      - src/auction_db.env
    volumes:
      - ./db/persistent:/var/lib/postgresql/data:z
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  redis:
    image: redis:6-alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 5s
      interval: 10s
      retries: 10
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    ports:
      - "6379:6379"